module.exports = {
  // https://github.com/dwyl/goodparts/issues/59
  "accessor-pairs": "error",
  // https://github.com/dwyl/goodparts/issues/61
  "block-scoped-var": "error",
  // https://github.com/dwyl/goodparts/issues/63
  "complexity": ["error", 10],
  // https://github.com/dwyl/goodparts/issues/65
  "curly": "error",
  // https://github.com/dwyl/goodparts/issues/68
  "dot-location": ["error", "property"],
  // https://github.com/dwyl/goodparts/issues/71
  "eqeqeq": ["error", "always"],
  // https://github.com/dwyl/goodparts/issues/72
  "no-alert": "error",
  // https://github.com/dwyl/goodparts/issues/74
  "no-case-declarations": "error",
  // https://github.com/dwyl/goodparts/issues/87
  "no-else-return": "error",
  // https://github.com/dwyl/goodparts/issues/88
  "no-empty-pattern": "error",
  // https://github.com/dwyl/goodparts/issues/89
  "no-eval": "error",
  // https://github.com/dwyl/goodparts/issues/90
  "no-extra-bind": "error",
  // https://github.com/dwyl/goodparts/issues/95
  "no-fallthrough": "error",
  // https://github.com/dwyl/goodparts/issues/97
  "no-global-assign": "error",
  // https://github.com/dwyl/goodparts/issues/110
  "no-implicit-globals": "error",
  // https://github.com/dwyl/goodparts/issues/115
  "no-invalid-this": "error",
  // https://github.com/dwyl/goodparts/issues/120
  "no-labels": "error",
  // https://github.com/dwyl/goodparts/issues/125
  "no-loop-func": "error",
  // https://github.com/dwyl/goodparts/issues/130
  "no-multi-spaces": "error",
  // https://github.com/dwyl/goodparts/issues/131
  "no-new-func": "error",
  // https://github.com/dwyl/goodparts/issues/133
  "no-new": "error",
  // https://github.com/dwyl/goodparts/issues/137
  "no-octal": "error",
  // https://github.com/dwyl/goodparts/issues/142
  "no-proto": "error",
  // https://github.com/dwyl/goodparts/issues/147
  "no-return-assign": ["error", "always"],
  // https://github.com/dwyl/goodparts/issues/159
  "no-self-assign": ["error", { props: true }],
  // https://github.com/dwyl/goodparts/issues/163
  "no-sequences": "error",
  // https://github.com/dwyl/goodparts/issues/166
  "no-unused-labels": "error",
  // https://github.com/dwyl/goodparts/issues/172
  "no-useless-concat": "error",
  // https://github.com/dwyl/goodparts/issues/178
  "no-unmodified-loop-condition": "error",
  // https://github.com/dwyl/goodparts/issues/179
  "no-void": "error",
  // https://github.com/dwyl/goodparts/issues/181
  "no-with": "error",
  // https://github.com/dwyl/goodparts/issues/182
  "vars-on-top": "error",
  // https://github.com/dwyl/goodparts/issues/183
  "yoda": ["error", "never", { exceptRange: true }],
  // https://github.com/dwyl/goodparts/issues/57
  'array-callback-return': 'error',
    // https://github.com/dwyl/goodparts/issues/58
  'class-methods-use-this': 'off',
  // https://github.com/dwyl/goodparts/issues/60
  'consistent-return': 'error',
  // https://github.com/dwyl/goodparts/issues/62
  'default-case': 'error',
  // https://github.com/dwyl/goodparts/issues/64
  'dot-notation': 'error',
  // https://github.com/dwyl/goodparts/issues/66
  'no-caller': 'error',
  // https://github.com/dwyl/goodparts/issues/67
  'guard-for-in': 'off',
  // https://github.com/dwyl/goodparts/issues/69
  'no-div-regex': 'error',
  // https://github.com/dwyl/goodparts/issues/70
  'no-empty-function': 'error',
  // https://github.com/dwyl/goodparts/issues/75
  'no-eq-null': 'error',
  // https://github.com/dwyl/goodparts/issues/77
  'no-extend-native': 'error',
  // https://github.com/dwyl/goodparts/issues/80
  'no-extra-label': 'error',
  // https://github.com/dwyl/goodparts/issues/81
  'no-floating-decimal': 'error',
  // https://github.com/dwyl/goodparts/issues/82
  'no-implicit-coercion': 'error',
  // https://github.com/dwyl/goodparts/issues/83
  'no-implied-eval': 'error',
  // https://github.com/dwyl/goodparts/issues/84
  'no-iterator': 'error',
  // https://github.com/dwyl/goodparts/issues/91
  'no-lone-blocks': 'error',
  // https://github.com/dwyl/goodparts/issues/92
  'no-magic-numbers': 'off',
  // https://github.com/dwyl/goodparts/issues/93
  'no-multi-str': 'error',
  // https://github.com/dwyl/goodparts/issues/94
  'no-new-wrappers': 'error',
  // https://github.com/dwyl/goodparts/issues/96
  'no-octal-escape': 'error',
  // https://github.com/dwyl/goodparts/issues/98
  'no-param-reassign': ['error', { props: false }],
  // https://github.com/dwyl/goodparts/issues/99
  'no-redeclare': 'error',
  // https://github.com/dwyl/goodparts/issues/105
  'no-script-url': 'error',
  // https://github.com/dwyl/goodparts/issues/106
  'no-self-compare': 'error',
  // https://github.com/dwyl/goodparts/issues/113
  'no-unused-expressions': 'error',
  // https://github.com/dwyl/goodparts/issues/114
  'no-useless-call': 'error',
  // https://github.com/dwyl/goodparts/issues/116
  'no-useless-escape': 'error',
  // https://github.com/dwyl/goodparts/issues/117
  'no-warning-comments': 'off',
  // https://github.com/dwyl/goodparts/issues/118
  'radix': ['error', 'always'],
};
