module.exports = {
  "yoda": ["error", "never", { exceptRange: true }],
  "vars-on-top": "error",
  "no-with": "error",
  "no-void": "error",
  "no-unmodified-loop-condition": "error",
  "no-useless-concat": "error",
  "no-unused-labels": "error",
  "no-sequences": "error",
  "no-self-assign": ["error", { props: true }],
  "no-return-assign": ["error", "always"],
  "no-proto": "error",
  "no-octal": "error",
  "no-new": "error",
  "no-new-func": "error",
  "no-multi-spaces": "error",
  "no-loop-func": "error",
  "no-labels": "error",
  "no-invalid-this": "error",
  "no-implicit-globals": "error",
  "no-global-assign": "error",
  "no-fallthrough": "error",
  "no-extra-bind": "error",
  "no-eval": "error",
  "no-empty-pattern": "error",
  "no-else-return": "error",
  "no-case-declarations": "error",
  "no-alert": "error",
  "eqeqeq": ["error", "always"],
  "dot-location": ["error", "property"],
  "curly": "error",
  "complexity": ["error", 10],
  "block-scoped-var": "error",
  "accessor-pairs": "error"
};
